daily:
  - name: 'pageviews'
    description: "Number of pageviews"
    source: 'Google Analytics'

  - name: 'unique_pageviews'
    description: "Number of unique pageviews"
    source: 'Google Analytics'

  - name: 'feedex_comments'
    description: "Number of reported content issues"
    source: 'Feedback explorer'

  - name: 'is_this_useful_no'
    description: "Total number of people who did not find the page helpful"
    source: 'Google Analytics'

  - name: 'is_this_useful_yes'
    description: "Total number of people who found the page helpful"
    source: 'Google Analytics'

  - name: 'number_of_internal_searches'
    description: "Number of times a user searches for something else on GOV.UK from the page"
    source: 'Google Analytics'

  - name: 'entrances'
    description: "Number of session that began with this page"
    source: 'Google Analytics'

  - name: 'exits'
    description: "Number of session that ended with this page"
    source: 'Google Analytics'

  - name: 'bounce_rate'
    description: "Number of sessions that started on this page and exited without viewing any others"
    source: 'Google Analytics'

  - name: 'avg_time_on_page'
    description: "Amount of time users spend on this page on average"
    source: 'Google Analytics'

edition:
  - name: 'number_of_pdfs'
    description: "Number of .pdf attachments"
    source: 'Publishing API'

  - name: 'number_of_word_files'
    description: "Number of .doc attachments"
    source: 'Publishing API'

  - name: 'readability_score'
    description: "Flesch-Kincaid Reading Ease score"

  - name: 'contractions_count'
    description: "Count of improper apostrophe use in contractions."
    source: 'retext'

  - name: 'equality_count'
    description: "Number of times potentially insensitive language is used"
    source: 'retext'

  - name: 'indefinite_article_count'
    description: "Number of times the indefinite articles (a, an) are used incorrectly"
    source: 'retext'

  - name: 'passive_count'
    description: "Number of times the passive voice is used"
    source: 'retext'

  - name: 'profanities_count'
    description: "Number of times profanities are used"
    source: 'retext'

  - name: 'redundant_acronyms_count'
    description: "Number of times redundant acronyms are used (like ATM machine instead of ATM)"
    source: 'retext'

  - name: 'repeated_words_count'
    description: 'Number of times a word is repeated (like "for for")'
    source: 'retext'

  - name: 'simplify_count'
    description: "Count of complicated words that have a simpler alternative"
    source: 'retext'

  - name: 'spell_count'
    description: "Number of spelling errors"
    source: 'retext'

  - name: 'string_length'
    description: "Total number of characters used in the text"
    source: 'custom'

  - name: 'sentence_count'
    description: "Total number of sentences detected in the text"
    source: 'custom'

  - name: 'word_count'
    description: "Total number of words detected in the text"
    source: 'custom'
