default: &default
  pageviews:
    description: "Number of pageviews"
    source: Google Analytics

  unique_pageviews:
    description: "Number of unique pageviews"
    source: Google Analytics

  feedex_comments:
    description: "Number of reported content issues"
    source: Feedback explorer

  number_of_pdfs:
    description: "Number of .pdf attachments"
    source: Publishing API

  number_of_word_files:
    description: "Number of .doc attachments"
    source: Publishing API

  readability_score:
    description: "Flesch-Kincaid Reading Ease score"

  contractions_count:
    description: "Count of improper apostrophe use in contractions."
    source: retext

  equality_count:
    description: "Number of times potentially insensitive language is used"
    source: retext

  indefinite_article_count:
    description: "Number of times the indefinite articles (a, an) are used incorrectly"
    source: retext

  passive_count:
    description: "Number of times the passive voice is used"
    source: retext

  profanities_count:
    description: "Number of times profanities are used"
    source: retext

  redundant_acronyms_count:
    description: "Number of times redundant acronyms are used (like ATM machine instead of ATM)"
    source: retext

  repeated_words_count:
    description: 'Number of times a word is repeated (like "for for")'
    source: retext

  simplify_count:
    description: "Count of complicated words that have a simpler alternative"

  spell_count:
    description: "Number of spelling errors"

  string_length:
    description: "Total number of characters used in the text"

  sentence_count:
    description: "Total number of sentences detected in the text"

  word_count:
    description: "Total number of words detected in the text"

  is_this_useful_no:
    description: "Total number of people who did not find the page helpful"
    source: Google Analytics

  is_this_useful_yes:
    description: "Total number of people who found the page helpful"
    source: Google Analytics

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
